
//Account module
export const ACCOUNT_LIST='Accounts';
export const ACCOUNT_DETAILS='Account Details';
export const ACCOUNT_CREATE = 'Create Account';
export const ACCOUNT_REAC = 'Reactivate Account';
export const ACCOUNT_SPND = 'Suspend Account';
export const ACCOUNT_CLOSE = 'Close Account';

//Account module
export const CONNECTIONS = 'CONNECTIONS';

//Miscelleneous
export const MISCELLENEOUS = 'Miscelleneous';
export const TOOLBOX_SEARCH = 'TOOLBOX_SEARCH';
export const USER_MANAGEMENT = 'User Management';
export const COUNTRY_MANAGEMENT = 'Country Management';

//Users
export const MISC_USERS = 'MISC_USERS';
export const MISC_USERLIST_REQUEST = 'MISC_USERLIST_REQUEST';
export const MISC_USERLIST_RESPONSE = 'MISC_USERLIST_RESPONSE';
export const MISC_USERDETAILS_REQUEST = 'MISC_USERDETAILS_REQUEST';
export const MISC_USERDETAILS_RESPONSE = 'MISC_USERDETAILS_RESPONSE';
export const MISC_UPDATE_USERDETAILS_REQUEST = 'MISC_UPDATE_USERDETAILS_REQUEST';
export const MISC_UPDATE_USERDETAILS_RESPONSE = 'MISC_UPDATE_USERDETAILS_RESPONSE';

//Countries
export const MISC_COUNTRYLIST_REQUEST = 'MISC_COUNTRYLIST_REQUEST';
export const MISC_COUNTRYLIST_RESPONSE = 'MISC_COUNTRYLIST_RESPONSE';
export const MISC_COUNTRYDETAILS_REQUEST = 'MISC_COUNTRYDETAILS_REQUEST';
export const MISC_COUNTRYDETAILS_RESPONSE = 'MISC_COUNTRYDETAILS_RESPONSE';
export const MISC_UPDATE_COUNTRYDETAILS_RESPONSE = 'MISC_UPDATE_COUNTRYDETAILS_RESPONSE';
export const MISC_UPDATE_COUNTRYDETAILS_REQUEST = 'MISC_UPDATE_COUNTRYDETAILS_REQUEST';
