
//menus
export const TOOLBOX_SEARCH = 'TOOLBOX_SEARCH';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';
export const ACCOUNT_MGMT='ACCOUNT_MGMT';
export const ACCOUNT_SETUP='ACCOUNT_SETUP';
export const MISC_USERS = 'MISC_USERS';
export const ACCOUNT_SPND = 'ACCOUNT_SPND';

//Miscelleneous
//Users
export const MISC_USERLIST_REQUEST = 'MISC_USERLIST_REQUEST';
export const MISC_USERLIST_RESPONSE = 'MISC_USERLIST_RESPONSE';
export const MISC_USERDETAILS_REQUEST = 'MISC_USERDETAILS_REQUEST';
export const MISC_USERDETAILS_RESPONSE = 'MISC_USERDETAILS_RESPONSE';
export const MISC_UPDATE_USERDETAILS_REQUEST = 'MISC_UPDATE_USERDETAILS_REQUEST';
export const MISC_UPDATE_USERDETAILS_RESPONSE = 'MISC_UPDATE_USERDETAILS_RESPONSE';

//
export const INLINE_EDIT_SET_VALUE = 'INLINE_EDIT_SET_VALUE';
