//Navigation
export const ACTIVE_NAV_ITEM = 'ACTIVE_NAV_ITEM';

//Account module
export const ACCOUNT_LIST='Accounts';
export const ACCOUNT_DETAILS='Account Details';
export const ACCOUNT_CREATE = 'Create Account';
// export const ACCOUNT_REAC = 'Reactivate Account';
// export const ACCOUNT_SPND = 'Suspend Account';
// export const ACCOUNT_CLOSE = 'Close Account';


export const ACCOUNT_COMMINFO_NEXT='ACCOUNT_COMMINFO_NEXT';
export const ACCOUNT_TECHDETAILS_BACK='ACCOUNT_TECHDETAILS_BACK';
export const ACCOUNT_TECHDETAILS_NEXT='ACCOUNT_TECHDETAILS_NEXT';
export const ACCOUNT_INTERFACEDETAILS_BACK='ACCOUNT_INTERFACEDETAILS_BACK';
export const ACCOUNT_INTERFACEDETAILS_NEXT='ACCOUNT_INTERFACEDETAILS_NEXT';
export const ACCOUNT_REVIEWDETAILS_BACK='ACCOUNT_REVIEWDETAILS_BACK';

export const CREATE_ACCOUNT_TYPE = 'CREATE_ACCOUNT_TYPE';
export const ACCOUNT_CREATE_NEW='ACCOUNT_CREATE_NEW';
export const ACCOUNT_CREATE_NEW_SUCCESS='ACCOUNT_CREATE_NEW_SUCCESS';
export const ACCOUNT_CREATE_NEW_FAILURE='ACCOUNT_CREATE_NEW_FAILURE';


export const ACCOUNT_MT_ROUTING_OPERATOR = 'ACCOUNT_MT_ROUTING_OPERATOR';
export const ACCOUNT_MT_ROUTING_SMSC = 'ACCOUNT_MT_ROUTING_SMSC';
export const ACCOUNT_MT_ROUTING_ONOFF = 'ACCOUNT_MT_ROUTING_ONOFF';
export const ACCOUNT_MT_ROUTING_PERMANENT = 'ACCOUNT_MT_ROUTING_PERMANENT';
export const ACCOUNT_MT_ROUTING_TPOA = 'ACCOUNT_MT_ROUTING_TPOA';


export const SUSPEND_ACC_COMPANY = 'SUSPEND_ACC_COMPANY';
export const SUSPEND_ACC_ACCOUNT = 'SUSPEND_ACC_ACCOUNT';
export const SUSPEND_ACC_INFO = 'SUSPEND_ACC_INFO';


export const ACCOUNT_MODIFY_MT_ROUTING_SMSC = 'ACCOUNT_MODIFY_MT_ROUTING_SMSC';
export const ACCOUNT_MODFIY_MT_ROUTING_ONOFF = 'ACCOUNT_MODFIY_MT_ROUTING_ONOFF';
export const ACCOUNT_MODIFY_MT_ROUTING_PERMANENT = 'ACCOUNT_MODIFY_MT_ROUTING_PERMANENT';
export const ACCOUNT_MODIFY_MT_ROUTING_TPOA = 'ACCOUNT_MODIFY_MT_ROUTING_TPOA';
export const ACCOUNT_MODIFY_MT_ROUTING_STARTTIME = 'ACCOUNT_MODIFY_MT_ROUTING_STARTTIME';


export const INFO_GENERAL_COMMERCIAL = 'INFO_GENERAL_COMMERCIAL';
export const INFO_GENERAL_SYBASE = 'INFO_GENERAL_SYBASE';
export const INFO_GENERAL_ACC_CONTACTS = 'INFO_GENERAL_ACC_CONTACTS';
export const INFO_GENERAL_TECHNICAL = 'INFO_GENERAL_TECHNICAL';
export const INFO_GENERAL_VOLUME = 'INFO_GENERAL_VOLUME';
export const INFO_GENERAL_MTSETTING = 'INFO_GENERAL_MTSETTING';
export const INFO_GENERAL_MOSETTING = 'INFO_GENERAL_MOSETTING';
export const INFO_GENERAL_DELIVERY = 'INFO_GENERAL_DELIVERY';


export const TPOA_ADD_SMSC = 'TPOA_ADD_SMSC';
export const TPOA_ADD_TPOA = 'TPOA_ADD_TPOA';
export const TPOA_DEDICATED_SMSC = 'TPOA_DEDICATED_SMSC';
export const TPOA_DEDICATED_SERVICE = 'TPOA_DEDICATED_SERVICE';
export const TPOA_DEDICATED_RETURNED_TPDA = 'TPOA_DEDICATED_RETURNED_TPDA';
export const TPOA_DEDICATED_CRITERIA = 'TPOA_DEDICATED_CRITERIA';
export const TPOA_PARSED_SMSC = 'TPOA_PARSED_SMSC';
export const TPOA_PARSED_SERVICE = 'TPOA_PARSED_SERVICE';
export const TPOA_PARSED_RETURNED_TPDA = 'TPOA_PARSED_RETURNED_TPDA';
export const TPOA_PARSED_CRITERIA = 'TPOA_PARSED_CRITERIA';
export const TPOA_PARSED_PFIELD = 'TPOA_PARSED_PFIELD';
export const TPOA_PARSED_KEYWORD_CRITERIA = 'TPOA_PARSED_KEYWORD_CRITERIA';
export const TPOA_PARSED_KEYWORD = 'TPOA_PARSED_KEYWORD';


export const ADDCONTACT_EXISTINGCOMPANY = 'ADDCONTACT_EXISTINGCOMPANY';
export const ADDCONTACT_COMPANYNAME = 'ADDCONTACT_COMPANYNAME';
export const ADDCONTACT_COMPANYEMAIL = 'ADDCONTACT_COMPANYEMAIL';
export const ADDCONTACT_COUNTRY = 'ADDCONTACT_COUNTRY';
export const ADDCONTACT_MOBILENUMBER = 'ADDCONTACT_MOBILENUMBER';
export const ADDCONTACT_DIRECTNUMBER = 'ADDCONTACT_DIRECTNUMBER';
export const ADD_CONTACT = 'ADD_CONTACT';



export const REACTIVATE_ACC_COMPANY = 'REACTIVATE_ACC_COMPANY';
export const REACTIVATE_ACC_ACCOUNT = 'REACTIVATE_ACC_ACCOUNT';
export const REACTIVATE_ACC_INFO = 'REACTIVATE_ACC_INFO';


export const CLOSE_ACC_COMPANY = 'CLOSE_ACC_COMPANY';
export const CLOSE_ACC_ACCOUNT = 'CLOSE_ACC_ACCOUNT';
export const CLOSE_ACC_INFO = 'CLOSE_ACC_INFO';






//Connections module
export const CONNECTIONS = 'CONNECTIONS';

//Miscelleneous
export const MISCELLENEOUS = 'Miscelleneous';
export const TOOLBOX_SEARCH = 'TOOLBOX_SEARCH';
export const USER_MANAGEMENT = 'User Management';
export const COUNTRY_MANAGEMENT = 'Country Management';

//Users
export const MISC_USERS = 'MISC_USERS';
export const MISC_USERLIST_REQUEST = 'MISC_USERLIST_REQUEST';
export const MISC_USERLIST_RESPONSE = 'MISC_USERLIST_RESPONSE';
export const MISC_USERDETAILS_REQUEST = 'MISC_USERDETAILS_REQUEST';
export const MISC_USERDETAILS_RESPONSE = 'MISC_USERDETAILS_RESPONSE';
export const MISC_UPDATE_USERDETAILS_REQUEST = 'MISC_UPDATE_USERDETAILS_REQUEST';
export const MISC_UPDATE_USERDETAILS_RESPONSE = 'MISC_UPDATE_USERDETAILS_RESPONSE';

//Countries
export const MISC_COUNTRYLIST_REQUEST = 'MISC_COUNTRYLIST_REQUEST';
export const MISC_COUNTRYLIST_RESPONSE = 'MISC_COUNTRYLIST_RESPONSE';
export const MISC_COUNTRYDETAILS_REQUEST = 'MISC_COUNTRYDETAILS_REQUEST';
export const MISC_COUNTRYDETAILS_RESPONSE = 'MISC_COUNTRYDETAILS_RESPONSE';
export const MISC_UPDATE_COUNTRYDETAILS_RESPONSE = 'MISC_UPDATE_COUNTRYDETAILS_RESPONSE';
export const MISC_UPDATE_COUNTRYDETAILS_REQUEST = 'MISC_UPDATE_COUNTRYDETAILS_REQUEST';

//Account list
export const MISC_ACCOUNT_LIST_REQUEST = 'MISC_ACCOUNT_LIST_REQUEST';
export const MISC_ACCOUNT_LIST_RESPONSE = 'MISC_ACCOUNT_LIST_RESPONSE';

//Company list
export const GET_COMPANY_LIST_REQUEST = 'GET_COMPANY_LIST_REQUEST';
export const GET_COMPANY_LIST_RESPONSE = 'GET_COMPANY_LIST_RESPONSE';

//Existing Contact list
export const GET_EX_CONTACT_LIST_REQUEST = 'GET_EX_CONTACT_LIST_REQUEST';
export const GET_EX_CONTACT_LIST_RESPONSE = 'GET_EX_CONTACT_LIST_RESPONSE';
export const GET_EX_CONTACT_DETAILS_REQUEST = 'GET_EX_CONTACT_DETAILS_REQUEST';
export const GET_EX_CONTACT_DETAILS_RESPONSE = 'GET_EX_CONTACT_DETAILS_RESPONSE';

//Billing location list
export const GET_BILLINGLOCATION_LIST_REQUEST = 'GET_BILLINGLOCATION_LIST_REQUEST';
export const GET_BILLINGLOCATION_LIST_RESPONSE = 'GET_BILLINGLOCATION_LIST_RESPONSE';

//SMSC list
export const GET_SMSC_LIST_REQUEST = 'GET_SMSC_LIST_REQUEST';
export const GET_SMSC_LIST_RESPONSE = 'GET_SMSC_LIST_RESPONSE';

//Volume Type list
export const GET_VOLUMETYPE_LIST_REQUEST = 'GET_VOLUMETYPE_LIST_REQUEST';
export const GET_VOLUMETYPE_LIST_RESPONSE = 'GET_VOLUMETYPE_LIST_RESPONSE';

//Delivery Time list
export const GET_STARTTIME_LIST_REQUEST = 'GET_STARTTIME_LIST_REQUEST';
export const GET_STARTTIME_LIST_RESPONSE = 'GET_STARTTIME_LIST_RESPONSE';
export const GET_ENDTIME_LIST_REQUEST = 'GET_ENDTIME_LIST_REQUEST';
export const GET_ENDTIME_LIST_RESPONSE = 'GET_ENDTIME_LIST_RESPONSE';

//Account General comm info
export const GET_ACCT_GENERAL_COMM_INFO_REQUEST = 'GET_ACCT_GENERAL_COMM_INFO_REQUEST';
export const GET_ACCT_GENERAL_COMM_INFO_RESPONSE = 'GET_ACCT_GENERAL_COMM_INFO_RESPONSE';
export const GET_ACCT_GENERAL_TECH_INFO_REQUEST = 'GET_ACCT_GENERAL_TECH_INFO_REQUEST';
export const GET_ACCT_GENERAL_TECH_INFO_RESPONSE = 'GET_ACCT_GENERAL_TECH_INFO_RESPONSE';
export const GET_ACCT_GENERAL_VOL_INFO_REQUEST = 'GET_ACCT_GENERAL_VOL_INFO_REQUEST';
export const GET_ACCT_GENERAL_VOL_INFO_RESPONSE = 'GET_ACCT_GENERAL_VOL_INFO_RESPONSE';
export const GET_ACCT_GENERAL_DELV_INFO_REQUEST = 'GET_ACCT_GENERAL_DELV_INFO_REQUEST';
export const GET_ACCT_GENERAL_DELV_INFO_RESPONSE = 'GET_ACCT_GENERAL_DELV_INFO_RESPONSE';

export const UPDATE_ACCT_GENERAL_COMM_INFO_REQUEST = 'UPDATE_ACCT_GENERAL_COMM_INFO_REQUEST';
export const UPDATE_ACCT_GENERAL_COMM_INFO_RESPONSE = 'UPDATE_ACCT_GENERAL_COMM_INFO_RESPONSE';
export const UPDATE_ACCT_GENERAL_TECH_INFO_REQUEST = 'UPDATE_ACCT_GENERAL_TECH_INFO_REQUEST';
export const UPDATE_ACCT_GENERAL_TECH_INFO_RESPONSE = 'UPDATE_ACCT_GENERAL_TECH_INFO_RESPONSE';
export const UPDATE_ACCT_GENERAL_VOL_INFO_REQUEST = 'UPDATE_ACCT_GENERAL_VOL_INFO_REQUEST';
export const UPDATE_ACCT_GENERAL_VOL_INFO_RESPONSE = 'UPDATE_ACCT_GENERAL_VOL_INFO_RESPONSE';
export const UPDATE_ACCT_GENERAL_DELV_INFO_REQUEST = 'UPDATE_ACCT_GENERAL_DELV_INFO_REQUEST';
export const UPDATE_ACCT_GENERAL_DELV_INFO_RESPONSE = 'UPDATE_ACCT_GENERAL_DELV_INFO_RESPONSE';

//Account TPOA info
export const GET_ACCT_DEFAULT_TPOA_REQUEST = 'GET_ACCT_DEFAULT_TPOA_REQUEST';
export const GET_ACCT_DEFAULT_TPOA_RESPONSE = 'GET_ACCT_DEFAULT_TPOA_RESPONSE';

export const GET_ACCT_FORCED_TPOA_LIST_REQUEST = 'GET_ACCT_FORCED_TPOA_LIST_REQUEST';
export const GET_ACCT_FORCED_TPOA_LIST_RESPONSE = 'GET_ACCT_FORCED_TPOA_LIST_RESPONSE';

export const SERVICE_LEVEL = [
    {"servicelevelname": "Standard", "servicelevelid": "1"},
      {"servicelevelname": "Premium", "servicelevelid": "2"}
];
export const LEGAL_STATUS = [
  { "legalstatusid" :1 , "legalstatusname" : "UNSIGNED"},
     { "legalstatusid" :2 , "legalstatusname" : "SIGNED"}
];
export const TRAFFIC_TYPE = [
     {"traffictypeid": 1, "traffictypename": "General"},
       {"traffictypeid": 2, "traffictypename": "Campaign"},
         {"traffictypeid": 3, "traffictypename": "Low Latency"},
           {"traffictypeid": 4, "traffictypename": "Time Sensitive"}
];
export const homepageOptions= [
    { homepageid: 1, homepagename: '/hubaccounts' },
    { homepageid: 2, homepagename: '/hubconnections' }
];

export const roleOptions= [
    { roleid: 'Support', rolename: 'Support' },
    { roleid: 'ServiceDesk', rolename: 'ServiceDesk' },
    { roleid: 'ACCOUNTMANAGER', rolename: 'ACCOUNTMANAGER'}
];
