//Auth
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//menus
export const TOOLBOX_SEARCH = 'TOOLBOX_SEARCH';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';


//Search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';

//
export const ACCOUNT_MGR_CHANGE='ACCOUNT_MGR_CHANGE';
export const ACCOUNT_COMPANY_CHANGE='ACCOUNT_COMPANY_CHANGE';
export const ACCOUNT_COMPANY_CONTACT='ACCOUNT_COMPANY_CONTACT';
export const ACCOUNT_COUNTRY_CHANGE='ACCOUNT_COUNTRY_CHANGE';
export const ACCOUNT_EXSTACCTS_CHANGE='ACCOUNT_EXSTACCTS_CHANGE';
export const ACCOUNT_INTERFACE_CHANGE='ACCOUNT_INTERFACE_CHANGE';
export const ACCOUNT_BILLING_LOCATION='ACCOUNT_BILLING_LOCATION';
export const SERVICE_LEVEL='SERVICE_LEVEL';
export const TRAFFIC_TYPE='TRAFFIC_TYPE';


export const ACCOUNT_NEXT='ACCOUNT_NEXT';
export const ACCOUNT_CREATE_NEW='ACCOUNT_CREATE_NEW';
export const ACCOUNT_CREATE_NEW_SUCCESS='ACCOUNT_CREATE_NEW_SUCCESS';
export const ACCOUNT_CREATE_NEW_FAILURE='ACCOUNT_CREATE_NEW_FAILURE';

