//Auth
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//menus
export const TOOLBOX_SEARCH = 'TOOLBOX_SEARCH';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';


//Search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';

//
export const ACCOUNT_MGR_CHANAGE='ACCOUNT_MGR_CHANAGE';
export const ACCOUNT_COMPANY_CHANAGE='ACCOUNT_COMPANY_CHANAGE';
export const ACCOUNT_COMPANY_CONTACT='ACCOUNT_COMPANY_CONTACT';
export const ACCOUNT_COUNTRY_CHANGE='ACCOUNT_COUNTRY_CHANGE';
export const ACCOUNT_NEXT='ACCOUNT_NEXT';


