

//


export const ACCOUNT_MGR_CHANGE='ACCOUNT_MGR_CHANGE';
export const ACCOUNT_COMPANY_CHANGE='ACCOUNT_COMPANY_CHANGE';
export const ACCOUNT_COMPANY_CONTACT='ACCOUNT_COMPANY_CONTACT';
export const ACCOUNT_COUNTRY_CHANGE='ACCOUNT_COUNTRY_CHANGE';
export const ACCOUNT_EXSTACCTS_CHANGE='ACCOUNT_EXSTACCTS_CHANGE';
export const ACCOUNT_INTERFACE_CHANGE='ACCOUNT_INTERFACE_CHANGE';
export const ACCOUNT_BILLING_LOCATION='ACCOUNT_BILLING_LOCATION';
export const ACCOUNT_SERVICE_LEVEL='SERVICE_LEVEL';
export const ACCOUNT_TRAFFIC_TYPE='TRAFFIC_TYPE';


export const ACCOUNT_COMMINFO_NEXT='ACCOUNT_COMMINFO_NEXT';
export const ACCOUNT_TECHDETAILS_BACK='ACCOUNT_TECHDETAILS_BACK';
export const ACCOUNT_TECHDETAILS_NEXT='ACCOUNT_TECHDETAILS_NEXT';
export const ACCOUNT_INTERFACEDETAILS_BACK='ACCOUNT_INTERFACEDETAILS_BACK';
export const ACCOUNT_INTERFACEDETAILS_NEXT='ACCOUNT_INTERFACEDETAILS_NEXT';
export const ACCOUNT_REVIEWDETAILS_BACK='ACCOUNT_REVIEWDETAILS_BACK';


export const ACCOUNT_CREATE_NEW='ACCOUNT_CREATE_NEW';
export const ACCOUNT_CREATE_NEW_SUCCESS='ACCOUNT_CREATE_NEW_SUCCESS';
export const ACCOUNT_CREATE_NEW_FAILURE='ACCOUNT_CREATE_NEW_FAILURE';

export const ACCOUNT_GET_COUNTRY_LIST='ACCOUNT_GET_COUNTRY_LIST';
export const ACCOUNT_GET_COUNTRY_LIST_SUCCESS='ACCOUNT_GET_COUNTRY_LIST_SUCCESS';
export const ACCOUNT_GET_COUNTRY_LIST_FAILURE='ACCOUNT_GET_COUNTRY_LIST_FAILURE';
