
export const ACCOUNT_MGR_CHANGE='ACCOUNT_MGR_CHANGE';
export const ACCOUNT_COMPANY_CHANGE='ACCOUNT_COMPANY_CHANGE';
export const ACCOUNT_COMPANY_CONTACT='ACCOUNT_COMPANY_CONTACT';
export const ACCOUNT_COUNTRY_CHANGE='ACCOUNT_COUNTRY_CHANGE';
export const ACCOUNT_EXSTACCTS_CHANGE='ACCOUNT_EXSTACCTS_CHANGE';
export const ACCOUNT_INTERFACE_CHANGE='ACCOUNT_INTERFACE_CHANGE';
export const ACCOUNT_BILLING_LOCATION='ACCOUNT_BILLING_LOCATION';
export const ACCOUNT_SERVICE_LEVEL='SERVICE_LEVEL';
export const ACCOUNT_TRAFFIC_TYPE='TRAFFIC_TYPE';


export const ACCOUNT_COMMINFO_NEXT='ACCOUNT_COMMINFO_NEXT';
export const ACCOUNT_TECHDETAILS_BACK='ACCOUNT_TECHDETAILS_BACK';
export const ACCOUNT_TECHDETAILS_NEXT='ACCOUNT_TECHDETAILS_NEXT';
export const ACCOUNT_INTERFACEDETAILS_BACK='ACCOUNT_INTERFACEDETAILS_BACK';
export const ACCOUNT_INTERFACEDETAILS_NEXT='ACCOUNT_INTERFACEDETAILS_NEXT';
export const ACCOUNT_REVIEWDETAILS_BACK='ACCOUNT_REVIEWDETAILS_BACK';


export const ACCOUNT_CREATE_NEW='ACCOUNT_CREATE_NEW';
export const ACCOUNT_CREATE_NEW_SUCCESS='ACCOUNT_CREATE_NEW_SUCCESS';
export const ACCOUNT_CREATE_NEW_FAILURE='ACCOUNT_CREATE_NEW_FAILURE';


export const ACCOUNT_GET_COUNTRY_LIST='ACCOUNT_GET_COUNTRY_LIST';
export const ACCOUNT_GET_COUNTRY_LIST_SUCCESS='ACCOUNT_GET_COUNTRY_LIST_SUCCESS';
export const ACCOUNT_GET_COUNTRY_LIST_FAILURE='ACCOUNT_GET_COUNTRY_LIST_FAILURE';


export const ACCOUNT_MT_ROUTING_OPERATOR = 'ACCOUNT_MT_ROUTING_OPERATOR';
export const ACCOUNT_MT_ROUTING_SMSC = 'ACCOUNT_MT_ROUTING_SMSC';
export const ACCOUNT_MT_ROUTING_ONOFF = 'ACCOUNT_MT_ROUTING_ONOFF';
export const ACCOUNT_MT_ROUTING_PERMANENT = 'ACCOUNT_MT_ROUTING_PERMANENT';
export const ACCOUNT_MT_ROUTING_TPOA = 'ACCOUNT_MT_ROUTING_TPOA';


export const SUSPEND_ACC_COMPANY = 'SUSPEND_ACC_COMPANY';
export const SUSPEND_ACC_ACCOUNT = 'SUSPEND_ACC_ACCOUNT';
export const SUSPEND_ACC_INFO = 'SUSPEND_ACC_INFO';


export const ACCOUNT_MODIFY_MT_ROUTING_SMSC = 'ACCOUNT_MODIFY_MT_ROUTING_SMSC';
export const ACCOUNT_MODFIY_MT_ROUTING_ONOFF = 'ACCOUNT_MODFIY_MT_ROUTING_ONOFF';
export const ACCOUNT_MODIFY_MT_ROUTING_PERMANENT = 'ACCOUNT_MODIFY_MT_ROUTING_PERMANENT';
export const ACCOUNT_MODIFY_MT_ROUTING_TPOA = 'ACCOUNT_MODIFY_MT_ROUTING_TPOA';
export const ACCOUNT_MODIFY_MT_ROUTING_STARTTIME = 'ACCOUNT_MODIFY_MT_ROUTING_STARTTIME';


export const INFO_GENERAL_COMMERCIAL = 'INFO_GENERAL_COMMERCIAL';
export const INFO_GENERAL_SYBASE = 'INFO_GENERAL_SYBASE';
export const INFO_GENERAL_ACC_CONTACTS = 'INFO_GENERAL_ACC_CONTACTS';
export const INFO_GENERAL_TECHNICAL = 'INFO_GENERAL_TECHNICAL';
export const INFO_GENERAL_VOLUME = 'INFO_GENERAL_VOLUME';
export const INFO_GENERAL_MTSETTING = 'INFO_GENERAL_MTSETTING';
export const INFO_GENERAL_MOSETTING = 'INFO_GENERAL_MOSETTING';
export const INFO_GENERAL_DELIVERY = 'INFO_GENERAL_DELIVERY';


export const TPOA_ADD_SMSC = 'TPOA_ADD_SMSC';
export const TPOA_ADD_TPOA = 'TPOA_ADD_TPOA';
export const TPOA_DEDICATED_SMSC = 'TPOA_DEDICATED_SMSC';
export const TPOA_DEDICATED_SERVICE = 'TPOA_DEDICATED_SERVICE';
export const TPOA_DEDICATED_RETURNED_TPDA = 'TPOA_DEDICATED_RETURNED_TPDA';
export const TPOA_DEDICATED_CRITERIA = 'TPOA_DEDICATED_CRITERIA';
export const TPOA_PARSED_SMSC = 'TPOA_PARSED_SMSC';
export const TPOA_PARSED_SERVICE = 'TPOA_PARSED_SERVICE';
export const TPOA_PARSED_RETURNED_TPDA = 'TPOA_PARSED_RETURNED_TPDA';
export const TPOA_PARSED_CRITERIA = 'TPOA_PARSED_CRITERIA';
export const TPOA_PARSED_PFIELD = 'TPOA_PARSED_PFIELD';
export const TPOA_PARSED_KEYWORD_CRITERIA = 'TPOA_PARSED_KEYWORD_CRITERIA';
export const TPOA_PARSED_KEYWORD = 'TPOA_PARSED_KEYWORD';


export const ADDCONTACT_EXISTINGCOMPANY = 'ADDCONTACT_EXISTINGCOMPANY';
export const ADDCONTACT_COMPANYNAME = 'ADDCONTACT_COMPANYNAME';
export const ADDCONTACT_COMPANYEMAIL = 'ADDCONTACT_COMPANYEMAIL';
export const ADDCONTACT_COUNTRY = 'ADDCONTACT_COUNTRY';
export const ADDCONTACT_MOBILENUMBER = 'ADDCONTACT_MOBILENUMBER';
export const ADDCONTACT_DIRECTNUMBER = 'ADDCONTACT_DIRECTNUMBER';


export const ACCOUNT_GET_COMPANY_LIST = 'ACCOUNT_GET_COMPANY_LIST';
export const ACCOUNT_GET_COMPANY_LIST_SUCCESS= 'ACCOUNT_GET_COMPANY_LIST_SUCCESS';
export const ACCOUNT_GET_COMPANY_LIST_FAILURE = 'ACCOUNT_GET_COMPANY_LIST_FAILURE';


export const REACTIVATE_ACC_COMPANY = 'REACTIVATE_ACC_COMPANY';
export const REACTIVATE_ACC_ACCOUNT = 'REACTIVATE_ACC_ACCOUNT';
export const REACTIVATE_ACC_INFO = 'REACTIVATE_ACC_INFO';


export const CLOSE_ACC_COMPANY = 'CLOSE_ACC_COMPANY';
export const CLOSE_ACC_ACCOUNT = 'CLOSE_ACC_ACCOUNT';
export const CLOSE_ACC_INFO = 'CLOSE_ACC_INFO';

//Navigation
export const ACTIVE_NAV_ITEM = 'ACTIVE_NAV_ITEM';
